//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SecurityModel
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class SecurityEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'SecurityEntities' 區段中找到的連接字串，初始化新的 SecurityEntities 物件。
        /// </summary>
        public SecurityEntities() : base("name=SecurityEntities", "SecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SecurityEntities 物件。
        /// </summary>
        public SecurityEntities(string connectionString) : base(connectionString, "SecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SecurityEntities 物件。
        /// </summary>
        public SecurityEntities(EntityConnection connection) : base(connection, "SecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<Access_Menu> Access_Menu
        {
            get
            {
                if ((_Access_Menu == null))
                {
                    _Access_Menu = base.CreateObjectSet<Access_Menu>("Access_Menu");
                }
                return _Access_Menu;
            }
        }
        private ObjectSet<Access_Menu> _Access_Menu;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 Access_Menu EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToAccess_Menu(Access_Menu access_Menu)
        {
            base.AddObject("Access_Menu", access_Menu);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecurityModel", Name="Access_Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Access_Menu : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 Access_Menu 物件。
        /// </summary>
        /// <param name="menuID">MenuID 屬性的初始值。</param>
        /// <param name="username">Username 屬性的初始值。</param>
        /// <param name="menuText">MenuText 屬性的初始值。</param>
        /// <param name="menuValuePath">MenuValuePath 屬性的初始值。</param>
        public static Access_Menu CreateAccess_Menu(global::System.Int32 menuID, global::System.String username, global::System.String menuText, global::System.String menuValuePath)
        {
            Access_Menu access_Menu = new Access_Menu();
            access_Menu.MenuID = menuID;
            access_Menu.Username = username;
            access_Menu.MenuText = menuText;
            access_Menu.MenuValuePath = menuValuePath;
            return access_Menu;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuText
        {
            get
            {
                return _MenuText;
            }
            set
            {
                OnMenuTextChanging(value);
                ReportPropertyChanging("MenuText");
                _MenuText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MenuText");
                OnMenuTextChanged();
            }
        }
        private global::System.String _MenuText;
        partial void OnMenuTextChanging(global::System.String value);
        partial void OnMenuTextChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuValuePath
        {
            get
            {
                return _MenuValuePath;
            }
            set
            {
                OnMenuValuePathChanging(value);
                ReportPropertyChanging("MenuValuePath");
                _MenuValuePath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MenuValuePath");
                OnMenuValuePathChanged();
            }
        }
        private global::System.String _MenuValuePath;
        partial void OnMenuValuePathChanging(global::System.String value);
        partial void OnMenuValuePathChanged();

        #endregion
    
    }

    #endregion
    
}
