//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SecurityModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SecurityEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SecurityEntities object using the connection string found in the 'SecurityEntities' section of the application configuration file.
        /// </summary>
        public SecurityEntities() : base("name=SecurityEntities", "SecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SecurityEntities object.
        /// </summary>
        public SecurityEntities(string connectionString) : base(connectionString, "SecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SecurityEntities object.
        /// </summary>
        public SecurityEntities(EntityConnection connection) : base(connection, "SecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Access_Menu> Access_Menu
        {
            get
            {
                if ((_Access_Menu == null))
                {
                    _Access_Menu = base.CreateObjectSet<Access_Menu>("Access_Menu");
                }
                return _Access_Menu;
            }
        }
        private ObjectSet<Access_Menu> _Access_Menu;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Access_Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccess_Menu(Access_Menu access_Menu)
        {
            base.AddObject("Access_Menu", access_Menu);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecurityModel", Name="Access_Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Access_Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Access_Menu object.
        /// </summary>
        /// <param name="menuID">Initial value of the MenuID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="menuText">Initial value of the MenuText property.</param>
        /// <param name="menuValuePath">Initial value of the MenuValuePath property.</param>
        public static Access_Menu CreateAccess_Menu(global::System.Int32 menuID, global::System.String username, global::System.String menuText, global::System.String menuValuePath)
        {
            Access_Menu access_Menu = new Access_Menu();
            access_Menu.MenuID = menuID;
            access_Menu.Username = username;
            access_Menu.MenuText = menuText;
            access_Menu.MenuValuePath = menuValuePath;
            return access_Menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuText
        {
            get
            {
                return _MenuText;
            }
            set
            {
                OnMenuTextChanging(value);
                ReportPropertyChanging("MenuText");
                _MenuText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MenuText");
                OnMenuTextChanged();
            }
        }
        private global::System.String _MenuText;
        partial void OnMenuTextChanging(global::System.String value);
        partial void OnMenuTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuValuePath
        {
            get
            {
                return _MenuValuePath;
            }
            set
            {
                OnMenuValuePathChanging(value);
                ReportPropertyChanging("MenuValuePath");
                _MenuValuePath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MenuValuePath");
                OnMenuValuePathChanged();
            }
        }
        private global::System.String _MenuValuePath;
        partial void OnMenuValuePathChanging(global::System.String value);
        partial void OnMenuValuePathChanged();

        #endregion
    
    }

    #endregion
    
}
